owner: adarsh-goel
repo: uptime

sites:
  - name: Portfolio
    url: https://itsadarsh.tech
  - name: Github
    url: https://github.com/adarsh-goel
  - name: Qbit server
    url: $QBIT
  - name: Cloud Server
    url: $CLOUD
  - name: Udemy Coupons
    url: https://udemy.itsadarsh.tech
status-website:
  theme: dark
  cname: status.itsadarsh.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Uptime Monitor**"
  introMessage: This is a status page which actively checks uptime of services and notifies incase of downtime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  assignees:
  - adarsh-goel
